In [15]:
# Step(1): Importing Libraries
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
# Step(2): Loading iris dataset
iris = sns.load_dataset('iris')
iris.head()

In [ ]:
# Step(3): Dropping the "species" column
iris.drop(labels = 'species', axis = 1, inplace = True)
iris.head()

In [ ]:
# Step(4): Adding columns
iris['sepal_sum'] = iris['sepal_length'] + iris['sepal_width']
iris['petal_sum'] = iris['petal_length'] + iris['petal_width']
iris.head()

In [40]:
# Step(5): Create table with mean, standard deviation, minimum, and maximum
mean = [np.mean(iris['sepal_length']), 
        np.mean(iris['sepal_width']),
        np.mean(iris['sepal_sum']),
        np.mean(iris['petal_length']),
        np.mean(iris['petal_width']),
        np.mean(iris['petal_sum'])]

std = [np.std(iris['sepal_length']), 
        np.std(iris['sepal_width']),
        np.std(iris['sepal_sum']),
        np.std(iris['petal_length']),
        np.std(iris['petal_width']),
        np.std(iris['petal_sum'])]

min = [np.min(iris['sepal_length']), 
        np.min(iris['sepal_width']),
        np.min(iris['sepal_sum']),
        np.min(iris['petal_length']),
        np.min(iris['petal_width']),
        np.min(iris['petal_sum'])]

max = [np.max(iris['sepal_length']), 
        np.max(iris['sepal_width']),
        np.max(iris['sepal_sum']),
        np.max(iris['petal_length']),
        np.max(iris['petal_width']),
        np.max(iris['petal_sum'])]


summary_dict = {'mean':mean, 'std':std, 'min':min, 'max':max}
summary_df = pd.DataFrame(data = summary_dict, index = list(iris.columns))
summary_df

                  mean       std  min   max
sepal_length  5.843333  0.825301  4.3   7.9
sepal_width   3.057333  0.434411  2.0   4.4
petal_length  8.900667  0.886303  6.8  11.7
petal_width   3.758000  1.759404  1.0   6.9
sepal_sum     1.199333  0.759693  0.1   2.5
petal_sum     4.957333  2.499316  1.2   9.2